import { PrismaClient, Semester, TypesGP } from "@prisma/client";

const prisma = new PrismaClient();

async function createLessonList() {
  try {
    await prisma.roadmap.deleteMany();
    const time = await prisma.users.createMany({
      data: [
        {
          user_id: "mk24c120",
          name: "Болормаа Амарсанаа",
          role: "student",
          school_year: 1,
          email: "amarsanaa@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk24c060",
          name: "Сэлэнгэ Аминаа",
          role: "student",
          school_year: 1,
          email: "aminaa@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk24c026",
          name: "Хангал Ананд",
          role: "student",
          school_year: 1,
          email: "anand@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk23c006",
          name: "Нарансүх Алтан-Оч",
          role: "student",
          school_year: 2,
          email: "altanoch@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk23c175",
          name: "Элбэгсайхан Нямзаяа",
          role: "student",
          school_year: 2,
          email: "Nyamzaya@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk23c218",
          name: "Дашбалбар Түвшинбат",
          role: "student",
          school_year: 2,
          email: "Tuvshinbat@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk22c022",
          name: "Батцэрэн Билгүүн",
          role: "student",
          school_year: 3,
          email: "bilguun@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk22c2111",
          name: "Төмөрбаатар Алтан-Очир",
          role: "student",
          school_year: 3,
          email: "altanochir@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk22c260",
          name: "Хүдэрбат Азжаргал",
          role: "student",
          school_year: 3,
          email: "azjargal@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk21c033",
          name: "Дарханбаатар Одбилэг",
          role: "student",
          school_year: 4,
          email: "Odbileg@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk21c060",
          name: "Мөнхжаргал Батхангал",
          role: "student",
          school_year: 4,
          email: "bathangal@gmail.com",
          password: "1234",
        },
        {
          user_id: "mk21c013",
          name: "Баатар Төгөлдөр",
          role: "student",
          school_year: 4,
          email: "tuguldur@gmail.com",
          password: "1234",
        },
      ],
    });

    const newLessonList = await prisma.roadmap.createMany({
      data: [
        {
          lesson_code: "KML103",
          lesson_name: "Уран зохиол I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
         
        },
        {
          lesson_code: "KML101",
          lesson_name: "Монгол хэл",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN102",
          lesson_name: "Англи хэл I B",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP101",
          lesson_name: "Япон хэл I A",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP102",
          lesson_name: "Япон хэл I B",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMT101",
          lesson_name: "Математик I",
          credits: 3,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KNS101",
          lesson_name: "Биологи",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KNS102",
          lesson_name: "Газар зүй",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCH101",
          lesson_name: "Хими I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH101",
          lesson_name: "Физик I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE102",
          lesson_name: "Биеийн тамир I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS103",
          lesson_name: "Цахилгаан хэлхээ I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS150",
          lesson_name: "Алгоритмын үндэс ба C хэл",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMS102",
          lesson_name: "Үндэсний бичиг I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN101",
          lesson_name: "Англи хэл I A",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP101",
          lesson_name: "Япон хэл I A",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP102",
          lesson_name: "Япон хэл I B",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KTM101",
          lesson_name: "Математик I",
          credits: 3,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPH101",
          lesson_name: "Физик I",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE101",
          lesson_name: "Эрүүл мэнд",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE102",
          lesson_name: "Биеийн тамир",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KIT101",
          lesson_name: "Мэдээллийн технологийн үндэс",
          credits: 2,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
 
        {
          lesson_code: "KEL101",
          lesson_name: "Бүтээх ухааны үндэс",
          credits: 1,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Программын хэлнүүдийн талаар үндсэн ойлголттой болно. Мөн Scratch программын ажлын орчинтой танилцана, ашиглаж сурна. Жижиг төслийн ажил хийж гүйцэтгэнэ.",
        },
        {
          lesson_code: "KML101",
          lesson_name: "Монгол хэл",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN102",
          lesson_name: "Англи хэл I B",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP101",
          lesson_name: "Япон хэл I A",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP102",
          lesson_name: "Япон хэл I B",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMT101",
          lesson_name: "Математик I",
          credits: 3,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KNS101",
          lesson_name: "Биологи",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KNS102",
          lesson_name: "Газар зүй",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCH101",
          lesson_name: "Хими I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH101",
          lesson_name: "Физик I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE102",
          lesson_name: "Биеийн тамир I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS103",
          lesson_name: "Цахилгаан хэлхээ I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
         
        },
        {
          lesson_code: "KCS150",
          lesson_name: "Алгоритмын үндэс ба C хэл",
          credits: 2,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Программчлалын хэлний суурь хэл болох С хэлний бүх төрлийн функцийг бүрэн ашиглан программ зохиож чаддаг болох. Өөрийн эргэн тойронд байх асуудлыг программын аргаар шийдэж болох гаргалгааг хайн илрүүлэх, алгоритм зохион тухайн алгоритмын дагуу программ зохиож чаддаг болох. Программын алдааг олон засах чадварт суралцах. Бэлэн программыг хараад ойлгох, өөрт хэрэгтэй функцийг программдаа хөрвүүлэн ашиглах, өөрийн зохиосон программыг бусдад тайлбарлах зэрэг чадварт суралцана. ",
        },
        {
          lesson_code: "KML203",
          lesson_name: "Уран зохиол II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN201",
          lesson_name: "Англи хэл II A",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN201",
          lesson_name: "Япон хэл II A",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN202",
          lesson_name: "Япон хэл II B",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KMT201",
          lesson_name: "Матеманик II",
          credits: 3,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCH201",
          lesson_name: "Хими II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE201",
          lesson_name: "Биеийн тамир II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS201",
          lesson_name: "Тоон хэлхээ I",
          credits: 1,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: ": Тооллын системийн үндсэн ойлголт, тооллын систем хооронд хувиргах, арифметик үйлдэл үзнэ. Мөн логик хэлхээний үндсэн элемент болох гэйтүүдийн онолын мэдлэг, Булийн алгебр,логик илэрхийллийг үнэний хүснэгтээс гаргаж авах, логик илэрхийллийн дагуу логик хэлхээг зурах талаар заана.",
        },
        {
          lesson_code: "KCS204",
          lesson_name: "Электроникийн хэлхээ I",
          credits: 1,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Хагас дамжуулагч материал түүний бүтэц физик шинж чанарыг ойлгож авсны дараа P болон N төрлийн хагас дамжуулагчаар диод болон транзистор хэрхэн хийдэг талаар судлана. Диод болон транзистор ашиглан хийсэн хэлхээний ажиллагааг тайлбарлана.",
        },
        {
          lesson_code: "KCS204",
          lesson_name: "Компьютерын ухааны туршилт I",
          credits: 1.5,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Нэгдүгээр улиралд ардуйногийн ерөнхий ойлголт, электроник программчлалын үндсэн ойлголт, электроникийн хялбар хэлхээг туршилтын хавтан дээр угсран, программ бичих дадлага ажил хийж гүйцэтгэнэ. Хоёрдугаар улиралд модуль элементүүдтэй харьцан ардуйногийн сангийн функцүүд судлан, практик хэрэглээ заана.",
        },
        {
          lesson_code: "KCS250",
          lesson_name: "Веб зохиомж I",
          credits: 2,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Веб сайт хийх үндсэн программчлалын хэл болох HTML, CSS, JS талаар судлана. HTML ашиглан хэрхэн веб хуудасны бүтцийг гаргах талаар үзнэ. Үүсгэсэн веб хуудасны загвар, загварыг өөрчлөхдөө CSS хэрхэн ашиглах талаар судална. JS ашиглан веб хуудсан үйлдэл болон динамик веб хуудас хийж сурна.",
        },
        {
          lesson_code: "KML201",
          lesson_name: "Монгол хэл,уран зохиол II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMS202",
          lesson_name: "Үндэсний бичиг II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KSS202",
          lesson_name: "Түүх",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN202",
          lesson_name: "Англи хэл II B",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP201",
          lesson_name: "Япон хэл II A",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP202",
          lesson_name: "Япон хэл II B",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KTM101",
          lesson_name: "Матеманик I",
          credits: 3,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH201",
          lesson_name: "Физик II",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE202",
          lesson_name: "Биеийн тамир II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS203",
          lesson_name: "Цахилгаан хэлхээ II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS206",
          lesson_name: "Компьютерын ухааны туршилт I",
          credits: 1.5,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Нэгдүгээр улиралд ардуйногийн ерөнхий ойлголт, электроник программчлалын үндсэн ойлголт, электроникийн хялбар хэлхээг туршилтын хавтан дээр угсран, программ бичих дадлага ажил хийж гүйцэтгэнэ. Хоёрдугаар улиралд модуль элементүүдтэй харьцан ардуйногийн сангийн функцүүд судлан, практик хэрэглээ заана.",
        },
        {
          lesson_code: "KCS251",
          lesson_name: "Веб зохиомж II",
          credits: 2,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "React нь JavaSript хэлэнд суурилсан user interface (UI) буюу хэрэглэгчийн харж, хэрэглэж буй тухайн нүүрэн хэсгийг зурах зорилготой гарсан сан (library) юм. Энэ санг ашиглан веб хуудас хэрхэн хийх талаар судална.",
        },
        {
          lesson_code: "KML303",
          lesson_name: "Уран зохиол III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KSS301",
          lesson_name: "Нийгмийн ухаан",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEC301",
          lesson_name: "Ирэгний ёс зүйн боловсрол",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN301",
          lesson_name: "Англи хэл III A",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP301",
          lesson_name: "Япон хэл III A",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP302",
          lesson_name: "Япон хэл III B",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KTM201",
          lesson_name: "Математик II",
          credits: 3,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPH301",
          lesson_name: "Физик III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE301",
          lesson_name: "Биеийн тамир III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS301",
          lesson_name: "Тоон хэлхээ II",
          credits: 1,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Тоон хэлхээ 2 хичээл нь тоон хэлхээ 1 хичээлийн үргэлжлэл хичээл. Дараалсан хэлхээ бүлэг сэдвийг энэ хичээлээр үзнэ. Оюутан санах ой болон санах ой элементүүд болох латч, flipflop-ийн ажиллагааг ойлгож авна. Тухайн элементүүдийг ашиглан регистр, тоолуур зэрэг дараалсан хэлхээнүүдийн ажиллагааг ойлгож авна. ",
        },
        {
          lesson_code: "KCS304",
          lesson_name: "Электроникийн хэлхээ II",
          credits: 1,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS306",
          lesson_name: "Компьютерын ухааны туршилт II",
          credits: 1.5,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Нэгдүгээр улиралд Raspberry Pi программчлах үндсэн ойлголт, хялбар программ бичнэ, төрөл бүрийн сенсор холбож туршилт ажил хийнэ. Хоёрдугаар улиралд Raspberry Pi Ai Car-ыг удирдах, өнгө таних, объектуудыг таних, саадыг тойрох туршилт ажил хийнэ.",
         
        },
        {
          lesson_code: "KCS350",
          lesson_name: "Мобайл технологи",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "React native framework ашиглан гар утасны апплекейшин хийх суурь мэдлэг, арга технологийг судлана.",
        },
        {
          lesson_code: "KCS310",
          lesson_name: "Хиймэл оюун ухаан ба пайтон",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KML301",
          lesson_name: "Монгол хэл III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KSS301",
          lesson_name: "Нийгмийн ухаан",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMS203",
          lesson_name: "Үндэсний бичиг III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN302",
          lesson_name: "Англи хэл III B",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP301",
          lesson_name: "Япон хэл III A",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP302",
          lesson_name: "Япон хэл III B",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KTM201",
          lesson_name: "Математик II",
          credits: 3,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH301",
          lesson_name: "Физик III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE301",
          lesson_name: "Биеийн тамир III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS306",
          lesson_name: "Компьтерын ухааны туршилт II",
          credits: 1.5,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Нэгдүгээр улиралд Raspberry Pi программчлах үндсэн ойлголт, хялбар программ бичнэ, төрөл бүрийн сенсор холбож туршилт ажил хийнэ. Хоёрдугаар улиралд Raspberry Pi Ai Car-ыг удирдах, өнгө таних, объектуудыг таних, саадыг тойрох туршилт ажил хийнэ.",
        },
        {
          lesson_code: "KCS351",
          lesson_name: "Веб систем ба технологи",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS310",
          lesson_name: "Хиймэл оюун ухаан ба пайтон",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS319",
          lesson_name: "Өгөгдлийн сангийн үндэс",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Алгоритмын үндэс ба C хэл ",
        },
        {
          lesson_code: "KMT301",
          lesson_name: "Математик III",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
          Description: "Математикийн боловсролын хэрэгцээ нь мэдээлэл, харилцаа, техник технологийн хөгжил давамгайлсан хүмүүнлэг иргэний ардчилсан нийгэмд ажиллаж амьдрах, иргэн бүрийг сонголт хийхдээ хариуцлагатай хандах, чөлөөт өрсөлдөөнд шударгаар оролцох зэрэг бодит шаардлагаар тодорхойлогдоно.",
        },
        {
          lesson_code: "KDM401",
          lesson_name: "Гамшгийн менежмент",
          credits: 1,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP401",
          lesson_name: "Япон хэл IV",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPH401",
          lesson_name: "Хэрэглээнмий физик",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS408",
          lesson_name: "Объект хандлагат программчлал",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Жава программчлалын хэлний үндсэн мэдлэг болон түүний программчлалын арга техникийг суралцаж, жава программчлалын хэлээр тооцооллын кодууд болон олон үйлдэлт кодыг бичиж сурах.  ",
        },
        {
          lesson_code: "KCS410",
          lesson_name: "Хиймэл оюун ухаан I",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Урьдчилсан боловсруулалт, моделийн үнэлгээ, модель сайжруулалт зэрэг машин сургалтын чухал процессууд болон удирдлагатай, удирдлагагүй машин сургалтын алгоритмууд, гүний сургалт, объект илрүүлэлтийн талаар судална. Мөн тэдгээрийг пайтон программчлалын хэл ашиглан хэрэгжүүлэх чадварыг эзэмшинэ.  ",  
        },
        {
          lesson_code: "KCS416",
          lesson_name: "Системийн программ хангамж",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Програм хангамжийн зохион бүтээх процесс болон үүнтэй холбоотой ашиглах арга, мэдээллийн хяналтын зарчим болон мэдээллийн аюулгүй байдлын техник ба ашиглалтын талаар сурна.   ",
        },
        {
          lesson_code: "KCS406",
          lesson_name: "Компьютерийн ухааны туршилт III",
          credits: 1.5,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Нэгдүгээр улиралд Raspberry Pi программчлах үндсэн ойлголт, хялбар программ бичнэ, модуль холбож туршилт ажил хийнэ. Хоёрдугаар улиралд тусгай зориулалтын протокол болох I2C ашиглан сенсорууд програмчлах туршилт ажил хийнэ.",
        },
        {
          lesson_code: "KCS405",
          lesson_name: "Компьютер техник хангамж",
          credits: 1,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS450",
          lesson_name: "Үүлэн тооцоолол",
          credits: 1,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KMT301",
          lesson_name: "Математик III",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
          Description: "Математикийн боловсролын хэрэгцээ нь мэдээлэл, харилцаа, техник технологийн хөгжил давамгайлсан хүмүүнлэг иргэний ардчилсан нийгэмд ажиллаж амьдрах, иргэн бүрийг сонголт хийхдээ хариуцлагатай хандах, чөлөөт өрсөлдөөнд шударгаар оролцох зэрэг бодит шаардлагаар тодорхойлогдоно.",
        },
 
        {
          lesson_code: "KJP401",
          lesson_name: "Япон хэл IV",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH401",
          lesson_name: "Хэрэглээнмий физик",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS410",
          lesson_name: "Хиймэл оюун ухаан I",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Урьдчилсан боловсруулалт, моделийн үнэлгээ, модель сайжруулалт зэрэг машин сургалтын чухал процессууд болон удирдлагатай, удирдлагагүй машин сургалтын алгоритмууд, гүний сургалт, объект илрүүлэлтийн талаар судална. Мөн тэдгээрийг пайтон программчлалын хэл ашиглан хэрэгжүүлэх чадварыг эзэмшинэ. ",
        },
        {
          lesson_code: "KCS406",
          lesson_name: "Компьютерын ухааны туршилт III",
          credits: 1.5,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Нэгдүгээр улиралд Raspberry Pi программчлах үндсэн ойлголт, хялбар программ бичнэ, модуль холбож туршилт ажил хийнэ. Хоёрдугаар улиралд тусгай зориулалтын протокол болох I2C ашиглан сенсорууд програмчлах туршилт ажил хийнэ.",
        },
        {
          lesson_code: "KCS411",
          lesson_name: "Үйлдлийн системийн онол",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Компьютерт суурилсан системийг ямар дарааллаар, ямар арга техник ашиглан хэрхэн хөгжүүлэх талаарх мэдлэгийг эзэмшинэ. Хэрэглэгчийн тавьсан шаардлагаас эхлээд түүнд тохирсон, өндөр чанартай программ хангамжийг гарган авах хүртэлх үе шатуудыг багаар хэрхэн хөгжүүлэх, ямар арга зүй, арга техникийг ашигладаг талаар онолын мэдлэг олгож, системийг хөгжүүлэх дадлага, чадвартай болгоно.  ",
        },
        {
          lesson_code: "KCS409",
          lesson_name: "Жава технологи",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "  Хичээл явагдах хэлбэр болон хичээлийн  агуулга  Н301 ангид семинар хэлбэрээр явуулж, материал зэргийг бүгдийг самбараас харах боломжтой байлгана. Хичээлийн хүрэх зорилтод чиглэсэн дасгалыг хичээл дээр өгч, хураалгах шаардлагатай дасгал ажлыг хураалгах хэлбэр, хугацааг тухайн үед хэлнэ. ",
        },
        {
          lesson_code: "KCS414",
          lesson_name: "Сүлжээний үндэс",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Энэ хичээлийг CISCO Networking Academy - Networking Basics курс дээр үндэслэн боловсруулсан болно. Энэ хичээл нь сүлжээний болон сүлжээний төхөөрөмжүүд, медиа, протоколуудын үндэс суурийг хамардаг.Оюутнууд сүлжээний даалгавруудыг биелүүлэхийн тулд янз бүрийн сүлжээний програмууд болон протоколуудыг хэрхэн ашиглах талаар суралцах болно.",
        },
        {
          lesson_code: "KCS480",
          lesson_name: "Үйлдвэрлэлийн дадлага",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "",
        },
        {
          lesson_code: "KCS412",
          lesson_name: "Программ хангамжийн зохиомж ба архитектур",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Компьютерт суурилсан системийг ямар дарааллаар, ямар арга техник ашиглан хэрхэн хөгжүүлэх талаарх мэдлэгийг эзэмшинэ. Хэрэглэгчийн тавьсан шаардлагаас эхлээд түүнд тохирсон, өндөр чанартай программ хангамжийг гарган авах хүртэлх үе шатуудыг багаар хэрхэн хөгжүүлэх, ямар арга зүй, арга техникийг ашигладаг талаар онолын мэдлэг олгож, системийг хөгжүүлэх дадлага, чадвартай болгоно. ",
        },
        {
          lesson_code: "KJP501",
          lesson_name: "Япон хэл V",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Намар,
          Description: "Япон хэлний хичээлээр оюутанд бодит нөхцөл байдалд хэрэглэгдэх ахисан шатны япон хэлийг судлана. Аливаа мэдээ мэдээллийг тодорхой төвшинд сонсож ойлгох, өөрийгөө илэрхийлэх ахисан шатны чадвар, дадал эзэмшин, япон соёлд суралцах үндсэн суурийг тавихад туслана. JLPTN3 түвшиний мэдлэг олгоно. ",
        },
        {
          lesson_code: "KMT401",
          lesson_name: "Хэрэглээний математик",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS506",
          lesson_name: "Компьютерын ухааны туршилт IV",
          credits: 3,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Инженерчлэлийн матлаб программчлалын орчинд ажиллах, үндсэн цонхнууд,скрипт файл үүсгэх, бодлого бодох, программ бичихийг заана.Матлаб-ын бие даасан программ хангамжуудын нэг нь болох симулинк программ судлан, динамик системийг загварчлах дүн шинжилгээ хийнэ",
        },
        {
          lesson_code: "KCS517",
          lesson_name: "Компьютер хараа",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS510",
          lesson_name: "Хиймэл оюун ухаан II",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS590",
          lesson_name: "Төгсөлтийн ажил",
          credits: 4,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
          Description: "Энэхүү хичээлийг судалснаар удирдагч багшийн удирдлаган доор судалгаа хийн, судалгааны төлөвлөгөө гаргах, туршилтын тоног төхөөрөмжийн программ хангамж, туршилт хийн, дүн шинжилгээ хийх зэрэг судалгаанд шаардлагатай чадварыг эзэмшинэ. Эрдэм шинжилгээний өгүүллэгийг ойлгон унших чадвар, судалгааны тайланг боловсруулах чадвар болон танилцуулга хийх чадварыг эзэмшинэ. ",
        },
        {
          lesson_code: "KJP501",
          lesson_name: "Япон хэл V",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
          Description: "Япон хэлний хичээлээр оюутанд бодит нөхцөл байдалд хэрэглэгдэх ахисан шатны япон хэлийг судлана. Аливаа мэдээ мэдээллийг тодорхой төвшинд сонсож ойлгох, өөрийгөө илэрхийлэх ахисан шатны чадвар, дадал эзэмшин, япон соёлд суралцах үндсэн суурийг тавихад туслана. JLPTN3 түвшиний мэдлэг олгоно. ",
        },
        {
          lesson_code: "KMT401",
          lesson_name: "Хэрэглээний математик",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS515",
          lesson_name: "Мэдээллийн нууцлал хамгаалалт",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Оюутнууд мэдээллийн технологийн аюулгүй байдлын талаар хүндсэн мэдлэг,ойлголтыгойлгож,өдөртутмынаюулгүйбайдлынхувьдкомпьютерийнсистем,сүлжээ,үйлчилгээ,хувийн мэдээлэлд учирч буй аюул занал, түүнээс урьдчилан сэргийлэх, бууруулах арга зэргийн мэдлэгийг эзэмшинэ.",
        },
        {
          lesson_code: "KCS510",
          lesson_name: "Хиймэл оюун ухаан II",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS590",
          lesson_name: "Төгсөлтийн ажил",
          credits: 4,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Энэхүү хичээлийг судалснаар удирдагч багшийн удирдлаган доор судалгаа хийн, судалгааны төлөвлөгөө гаргах, туршилтын тоног төхөөрөмжийн программ хангамж, туршилт хийн, дүн шинжилгээ хийх зэрэг судалгаанд шаардлагатай чадварыг эзэмшинэ. Эрдэм шинжилгээний өгүүллэгийг ойлгон унших чадвар, судалгааны тайланг боловсруулах чадвар болон танилцуулга хийх чадварыг эзэмшинэ. ",
        },
        {
          lesson_code: "KCS520",
          lesson_name: "Систем инженерчлэл",
          credits: 4,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
          Description: "Өмнө хагаст эзэмшсэн Линуксийн үндсэн мэдлэг,үндсэнүйлдлүүдийгашигланЛинуксдхэрэгждэгтөрөлбүрийнфункцуудын(шелл скрипт, GUI орчин, удирдлагын даалгавар, сүлжээний тохиргоо, аюулгүй байдал) агуулгыг ойлгож, тохиргоо болон хэрэгжилтийг хийж чаддаг болох.",
        },
      ],
    });
 
    console.log("Lesson List Created:", newLessonList);
  } catch (error) {
    console.error("Error creating Lesson List:", error);
  } finally {
    await prisma.$disconnect();
  }
}
 
createLessonList();
 