import { PrismaClient, Semester, TypesGP } from "@prisma/client";

const prisma = new PrismaClient();

async function createLessonList() {
  try {
    await prisma.roadmap.deleteMany();
    const time = await prisma.users.createMany({
      data: [
        {
          user_id: "mk24c120",
          name: "Болормаа Амарсанаа",
          role: "student",
          school_year: 1,
          email: "amarsanaa@gmail.com",
          password: "1234",
        },
      ],
    });
    const newLessonList = await prisma.roadmap.createMany({
      data: [
        {
          lesson_code: "KML103",
          lesson_name: "Уран зохиол I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KMS102",
          lesson_name: "Үндэсний бичиг I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN101",
          lesson_name: "Англи хэл I A",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP101",
          lesson_name: "Япон хэл I A",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP102",
          lesson_name: "Япон хэл I B",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KTM101",
          lesson_name: "Математик I",
          credits: 3,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPH101",
          lesson_name: "Физик I",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE101",
          lesson_name: "Эрүүл мэнд",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE102",
          lesson_name: "Биеийн тамир",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KIT101",
          lesson_name: "Мэдээллийн технологийн үндэс",
          credits: 2,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },

        {
          lesson_code: "KEL101",
          lesson_name: "Бүтээх ухааны үндэс",
          credits: 1,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KML101",
          lesson_name: "Монгол хэл",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN102",
          lesson_name: "Англи хэл I B",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP101",
          lesson_name: "Япон хэл I A",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP102",
          lesson_name: "Япон хэл I B",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMT101",
          lesson_name: "Математик I",
          credits: 3,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KNS101",
          lesson_name: "Биологи",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KNS102",
          lesson_name: "Газар зүй",
          credits: 2,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCH101",
          lesson_name: "Хими I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH101",
          lesson_name: "Физик I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE102",
          lesson_name: "Биеийн тамир I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS103",
          lesson_name: "Цахилгаан хэлхээ I",
          credits: 1,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS150",
          lesson_name: "Алгоритмын үндэс ба C хэл",
          credits: 2,
          school_year: 1,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KML203",
          lesson_name: "Уран зохиол II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN201",
          lesson_name: "Англи хэл II A",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN201",
          lesson_name: "Япон хэл II A",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN202",
          lesson_name: "Япон хэл II B",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KMT201",
          lesson_name: "Матеманик II",
          credits: 3,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCH201",
          lesson_name: "Хими II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE201",
          lesson_name: "Биеийн тамир II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS201",
          lesson_name: "Тоон хэлхээ I",
          credits: 1,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS204",
          lesson_name: "Электроникийн хэлхээ I",
          credits: 1,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS204",
          lesson_name: "Компьютерын ухааны туршилт I",
          credits: 1.5,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS250",
          lesson_name: "Веб зохиомж I",
          credits: 2,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KML201",
          lesson_name: "Монгол хэл,уран зохиол II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMS202",
          lesson_name: "Үндэсний бичиг II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KSS202",
          lesson_name: "Түүх",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN202",
          lesson_name: "Англи хэл II B",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP201",
          lesson_name: "Япон хэл II A",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP202",
          lesson_name: "Япон хэл II B",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KTM101",
          lesson_name: "Матеманик I",
          credits: 3,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH201",
          lesson_name: "Физик II",
          credits: 2,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE202",
          lesson_name: "Биеийн тамир II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS203",
          lesson_name: "Цахилгаан хэлхээ II",
          credits: 1,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS206",
          lesson_name: "Компьютерын ухааны туршилт I",
          credits: 1.5,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS251",
          lesson_name: "Веб зохиомж II",
          credits: 2,
          school_year: 2,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KML303",
          lesson_name: "Уран зохиол III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KSS301",
          lesson_name: "Нийгмийн ухаан",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEC301",
          lesson_name: "Ирэгний ёс зүйн боловсрол",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KEN301",
          lesson_name: "Англи хэл III A",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP301",
          lesson_name: "Япон хэл III A",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP302",
          lesson_name: "Япон хэл III B",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KTM201",
          lesson_name: "Математик II",
          credits: 3,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPH301",
          lesson_name: "Физик III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPE301",
          lesson_name: "Биеийн тамир III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS301",
          lesson_name: "Тоон хэлхээ II",
          credits: 1,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS304",
          lesson_name: "Электроникийн хэлхээ II",
          credits: 1,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS306",
          lesson_name: "Компьютерын ухааны туршилт II",
          credits: 1.5,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS350",
          lesson_name: "Мобайл технологи",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS310",
          lesson_name: "Хиймэл оюун ухаан ба пайтон",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KML301",
          lesson_name: "Монгол хэл III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KSS301",
          lesson_name: "Нийгмийн ухаан",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMS203",
          lesson_name: "Үндэсний бичиг III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KEN302",
          lesson_name: "Англи хэл III B",
          credits: 2,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP301",
          lesson_name: "Япон хэл III A",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP302",
          lesson_name: "Япон хэл III B",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KTM201",
          lesson_name: "Математик II",
          credits: 3,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH301",
          lesson_name: "Физик III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPE301",
          lesson_name: "Биеийн тамир III",
          credits: 1,
          school_year: 3,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS306",
          lesson_name: "Компьтерын ухааны туршилт II",
          credits: 1.5,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS351",
          lesson_name: "Веб систем ба технологи",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS310",
          lesson_name: "Хиймэл оюун ухаан ба пайтон",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS319",
          lesson_name: "Өгөгдлийн сангийн үндэс",
          credits: 2,
          school_year: 3,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMT301",
          lesson_name: "Математик III",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KDM401",
          lesson_name: "Гамшгийн менежмент",
          credits: 1,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP401",
          lesson_name: "Япон хэл IV",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KPH401",
          lesson_name: "Хэрэглээнмий физик",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS408",
          lesson_name: "Объект хандлагат программчлал",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS410",
          lesson_name: "Хиймэл оюун ухаан I",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS416",
          lesson_name: "Системийн программ хангамж",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS406",
          lesson_name: "Компьютерийн ухааны туршилт III",
          credits: 1.5,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS405",
          lesson_name: "Компьютер техник хангамж",
          credits: 1,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS450",
          lesson_name: "Үүлэн тооцоолол",
          credits: 1,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KMT301",
          lesson_name: "Математик III",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },

        {
          lesson_code: "KJP401",
          lesson_name: "Япон хэл IV",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KPH401",
          lesson_name: "Хэрэглээнмий физик",
          credits: 2,
          school_year: 4,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS410",
          lesson_name: "Хиймэл оюун ухаан I",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS406",
          lesson_name: "Компьютерын ухааны туршилт III",
          credits: 1.5,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS411",
          lesson_name: "Үйлдлийн системийн онол",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS409",
          lesson_name: "Жава технологи",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS414",
          lesson_name: "Сүлжээний үндэс",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS480",
          lesson_name: "Үйлдвэрлэлийн дадлага",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS412",
          lesson_name: "Программ хангамжийн зохиомж ба архитектур",
          credits: 2,
          school_year: 4,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KJP501",
          lesson_name: "Япон хэл V",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KMT401",
          lesson_name: "Хэрэглээний математик",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS506",
          lesson_name: "Компьютерын ухааны туршилт IV",
          credits: 3,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS517",
          lesson_name: "Компьютер хараа",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS510",
          lesson_name: "Хиймэл оюун ухаан II",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KCS590",
          lesson_name: "Төгсөлтийн ажил",
          credits: 4,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Намар,
        },
        {
          lesson_code: "KJP501",
          lesson_name: "Япон хэл V",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KMT401",
          lesson_name: "Хэрэглээний математик",
          credits: 2,
          school_year: 5,
          type: TypesGP.Gen,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS515",
          lesson_name: "Мэдээллийн нууцлал хамгаалалт",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS510",
          lesson_name: "Хиймэл оюун ухаан II",
          credits: 2,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS590",
          lesson_name: "Төгсөлтийн ажил",
          credits: 4,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
        {
          lesson_code: "KCS520",
          lesson_name: "Систем инженерчлэл",
          credits: 4,
          school_year: 5,
          type: TypesGP.Pro,
          semester: Semester.Хавар,
        },
      ],
    });

    console.log("Lesson List Created:", newLessonList);
  } catch (error) {
    console.error("Error creating Lesson List:", error);
  } finally {
    await prisma.$disconnect();
  }
}

createLessonList();
